language: node_js
node_js:
  - "6.11.5"
cache: yarn
branches:
  only: [master]
script:
  - yarn lint
  - yarn test
dist: trusty
notifications:
  webhooks: https://samson.zende.sk/integrations/travis/d38b401d7ce03f88566c997da29f42f3
